2019-05-26 16:04:18,281 INFO: Microblog startup [in /home/fk/py/microblog/app/__init__.py:43]
2019-05-26 16:04:28,698 ERROR: Exception on /login [POST] [in /home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/fk/py/microblog/app/routes.py", line 40, in login
    login_user(user, remember=form.remember_me.data)
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask_login/utils.py", line 158, in login_user
    if not force and not user.is_active:
AttributeError: 'NoneType' object has no attribute 'is_active'
2019-05-26 16:13:22,920 INFO: Microblog startup [in /home/fk/py/microblog/app/__init__.py:43]
2019-05-26 16:13:35,012 ERROR: Exception on /login [POST] [in /home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/fk/py/microblog/app/routes.py", line 40, in login
    login_user(user, remember=form.remember_me.data)
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask_login/utils.py", line 158, in login_user
    if not force and not user.is_active:
AttributeError: 'NoneType' object has no attribute 'is_active'
2019-05-26 16:14:08,573 ERROR: Exception on /login [POST] [in /home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/fk/py/microblog/app/routes.py", line 40, in login
    login_user(user, remember=form.remember_me.data)
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask_login/utils.py", line 158, in login_user
    if not force and not user.is_active:
AttributeError: 'NoneType' object has no attribute 'is_active'
2019-05-26 16:23:38,156 INFO: Microblog startup [in /home/fk/py/microblog/app/__init__.py:43]
2019-05-26 16:23:43,308 INFO: Microblog startup [in /home/fk/py/microblog/app/__init__.py:43]
2019-05-26 16:23:50,844 ERROR: Exception on /login [POST] [in /home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/fk/py/microblog/app/routes.py", line 40, in login
    login_user(user, remember=form.remember_me.data)
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask_login/utils.py", line 158, in login_user
    if not force and not user.is_active:
AttributeError: 'NoneType' object has no attribute 'is_active'
2019-05-26 16:23:57,096 ERROR: Exception on /login [POST] [in /home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/fk/py/microblog/app/routes.py", line 40, in login
    login_user(user, remember=form.remember_me.data)
  File "/home/fk/py/microblog/venv/lib/python2.7/site-packages/flask_login/utils.py", line 158, in login_user
    if not force and not user.is_active:
AttributeError: 'NoneType' object has no attribute 'is_active'
2019-05-26 16:25:22,869 INFO: Microblog startup [in /home/fk/py/microblog/app/__init__.py:43]
2019-05-26 16:30:52,171 INFO: Microblog startup [in /home/fk/py/microblog/app/__init__.py:43]
2019-05-27 10:46:12,867 INFO: Microblog startup [in /home/fk/py/microblog/app/__init__.py:43]
2019-05-27 10:46:27,783 INFO: Microblog startup [in /home/fk/py/microblog/app/__init__.py:43]
2019-05-27 10:59:48,797 INFO: Microblog startup [in /home/fk/py/microblog/app/__init__.py:43]
2019-05-27 11:06:08,490 INFO: Microblog startup [in /home/fk/py/microblog/app/__init__.py:43]
2019-05-27 11:46:06,841 INFO: Microblog startup [in /home/fk/py/microblog/app/__init__.py:43]
2019-05-27 11:58:58,588 INFO: Microblog startup [in /home/fk/py/microblog/app/__init__.py:43]
2019-05-27 12:01:47,594 INFO: Microblog startup [in /home/fk/py/microblog/app/__init__.py:43]
2019-05-27 12:05:08,534 INFO: Microblog startup [in /home/fk/py/microblog/app/__init__.py:43]
2019-05-27 12:07:20,728 INFO: Microblog startup [in /home/fk/py/microblog/app/__init__.py:43]
2019-05-27 12:14:54,238 INFO: Microblog startup [in /home/fk/py/microblog/app/__init__.py:43]
2019-05-27 12:15:07,761 INFO: Microblog startup [in /home/fk/py/microblog/app/__init__.py:43]
